language: c
# language: haskell
# ghc:
#   - 7.6
#   - 7.8

sudo: false

cache:
  apt: true
  directories:
  - $HOME/7.6.3/.cabal
  - $HOME/7.6.3/.ghc
  - $HOME/7.6.3/.stack
  - $HOME/7.8.4/.cabal
  - $HOME/7.8.4/.ghc
  - $HOME/7.8.4/.stack
  - $HOME/7.10.3/.cabal
  - $HOME/7.10.3/.ghc
  - $HOME/7.10.3/.stack

before_cache:
  - rm -rf $HOME/.cabal/logs $HOME/.cabal/packages/*/build-reports.log
  - export HOME=$OLDHOME

before_install:
  - mkdir $GHCVER
  - export OLDHOME=$HOME
  - export HOME=$HOME/$GHCVER
  - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/happy/1.19.5/bin:$PATH
  - wget https://www.stackage.org/stack/linux-x86_64 -O stack.tar.gz
  - mkdir stack-bin
  - tar zxf stack.tar.gz --strip-components=1 --wildcards -C stack-bin '*/stack'
  - export PATH=$(pwd)/stack-bin:$PATH
  - stack --version

install:
  - cabal update
  - happy --version
  - git clone --depth=1 https://github.com/DanielG/cabal-helper.git
  - cabal install cabal-helper/ --constraint "Cabal == ${CABALVER}.*"
  - cabal install -j --only-dependencies --enable-tests
  - '[[ "$GHCVER" == "7.10.3" ]] && cabal install cabal-install --constraint "cabal-install == ${CABALVER}.*" || :'
  - cabal --version
  - which cabal
  - which hsc2hs


script:
  - touch ChangeLog # Create ChangeLog if we're not on the release branch
  - cabal check
  - cabal sdist
  - export SRC_TGZ="$PWD/dist/$(cabal info . | awk '{print $2 ".tar.gz";exit}')"
  - rm -rf /tmp/test && mkdir -p /tmp/test
  - cd /tmp/test
  - tar -xf $SRC_TGZ && cd ghc-mod*/
  - cabal configure --enable-tests $WERROR
  - cabal build $JOBS
  - export ghc_mod_datadir=$PWD
  - cabal test

matrix:
  include:
  - env: GHCVER=7.6.3 CABALVER=1.16
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.6.3
        - cabal-install-1.16
        - happy-1.19.5
  - env: GHCVER=7.8.4 CABALVER=1.18 WERROR=--ghc-option=-Werror
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.8.4
        - cabal-install-1.18
        - happy-1.19.5
  - env: GHCVER=7.10.3 CABALVER=1.22 WERROR=--ghc-option=-Werror JOBS=-j1
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.10.3
        - cabal-install-1.22
        - happy-1.19.5
