all:
	piki template.html index.piki > index.html
	piki template.html install.piki > install.html
	piki template.html ghc-mod.piki > ghc-mod.html
	piki template.html ghc-modi.piki > ghc-modi.html
	piki template.html emacs.piki > emacs.html
	piki template.html preparation.piki > preparation.html
	piki template.html copyright.piki > copyright.html
	piki template.html history.piki > history.html
	piki template.html bug.piki > bug.html
